### ISSUE TITLE
Issue while using Multiple JWTToken Bearer

### ISSUE THREAD

**Issue by rohitkle** [graphql-aspnet/graphql-aspnet#58] opened 2022-02-16 00:32 UTC
Hi,

we have a requirement to add multiple jwt token bearer. One using the B2C authentication and other Azure AD authentication.
Following is the code snippet from the Startup.cs class.

services.AddAuthentication()
                .AddJwtBearer("AzureAD", options =>
                {
                 
                    options.Authority = $"XXXXXXXXXXXXXX";
                    options.Audience = $"XXXXXXXXXXXXXX";
                    
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidIssuer = $"XXXXXXXX",
                        ValidAudience = $"XXXXXXXXXXXXXX",
                    };
                })
             .AddJwtBearer("B2C",options =>
              {
                  options.Audience = $"XXXXXXXXXXXXXX";
                  options.Authority = $"XXXXXXXXXXXXXX";                  
                  options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                  {
                      ValidAudience = $"XXXXXXXXXXXXXX",
                      ValidIssuer = $"XXXXXXXXXXXXXX"
                  };
              });

            services.AddAuthorization(options =>
            {
                var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(
                    "B2C",
                    "AzureAD");
                defaultAuthorizationPolicyBuilder =
                    defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
                options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
            });

It works if we change the route attribute in the controller to use ASP.NET Route attribute but breaks if we use GraphRoute attribute at the controller level.

**Works:**
[Authorize]  
    [Route("abc")]
    public class AbcController : GraphController
    {
	}

**Error:**
[Authorize]  
    **[GraphRoute("abc")]**
    public class AbcController : GraphController
    {
	}

Request you kindly help us in solving the problem.

**Comment by kevin-carroll** [comment] 2022-02-16 01:16
Hi @rohitkle ,

Thanks for bringing this up. Can you provide a few more details on what you mean when you say "It breaks when we use the GraphRoute attribute"?  

What breaks exactly? Are you getting an exception or does it just not authorize as you'd expect?  Does only one of the two JWTs work or neither of them? 

This sounds like it may be a bug with the libraries routing mechanisms for authenticated requests but I need a bit more info on what you're seeing to be sure. I'll try and replicate the issue but any additional details you can provide would be most helpful.

Cheers,
Kevin

**Comment by rohitkle** [comment] 2022-02-16 09:44
Hi Kevin,

Thanks for the response.
we getting unauthorised error with no further details. neither of the JWT's work.

**GraphQL.AspNet: Warning: Field Auth Challenge Completed | Id: 97e6cceb,  Path: '[query]/abc/fields', Status: Unauthorized**

**Comment by markcunninghamuk** [comment] 2022-02-16 11:58
I also have this issue, It seems to be when you register 2 Authentication Providers (B2C and Azure AD) only one of the options works. It is almost like the code is somewhere taking the firstOrDefault() scheme. Happy to share on a call if that helps you.

**Comment by kevin-carroll** [comment] 2022-02-17 22:13
Thank you both for your feedback. I've been able to replicate the issue.

Long story short, the global default and fallback policies are being ignored during the authentication step. Instead the library is relying on a default auth scheme to be supplied on `AddAuthentication()` to determine an acceptable scheme for authenticating the user before passing it off for authorization.  

This is not the intended behavior. Both default and fallback policies should be honored as one would expect. A fix is in the works and should be available soon.

Cheers,
Kevin

**Comment by rohitkle** [comment] 2022-02-18 12:26
Great!

Thanks Kevin

**Comment by kevin-carroll** [comment] 2022-02-20 22:19
`v0.9.2-beta` was published today and should resolve this issue. Please let me know if you have any success with it or if further investigation is needed.

Cheers,
Kevin

**Comment by rohitkle** [comment] 2022-02-20 22:55
Hi Kevin,

Thanks for your help and quick fix. Yes, able to do multiple jwt token bearer. Did quick test using both B2C authentication and Azure AD authentication.

Will do further testing and will keep you posted.

Thanks again for your help and quick fix.

Cheers
Rohit

**Comment by kevin-carroll** [comment] 2022-02-27 18:03
closing as resolved. Please reopen or submit a new issue if needed.

**Closed by kevin-carroll** 2022-02-27 18:03 UTC
Labels: bug
