### ISSUE TITLE
Allow same Enum Value

### ISSUE THREAD

**Issue by jasonkolodziej** [graphql-aspnet/graphql-aspnet#20] opened 2021-01-29 00:22 UTC
really hoping to help you out as much as possible (:
Consider the following
```c-sharp
// Cc.cs
    [GraphType]
    [Description("CC")]
     public enum Cc : uint
    {
        None = 0,
        First = 287,
        NvUndefineSpaceSpecial = 287,
        EvictControl = 288,
// Omitted for brevity
```
```shell
      Application startup exception
      System.ArgumentException: An item with the same key has already been added. Key: NVUNDEFINESPACESPECIAL
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at GraphQL.AspNet.Defaults.TypeMakers.EnumGraphTypeMaker.CreateGraphType(Type concreteType)
         at GraphQL.AspNet.Schemas.GraphSchemaManager.EnsureGraphType(Type type, Nullable`1 kind)
         at GraphQL.AspNet.Execution.GraphSchemaInitializer.Initialize(ISchema schema)
         at GraphQL.AspNet.Configuration.Mvc.GraphQLSchemaInjector`1.BuildNewSchemaInstance(IServiceProvider serviceProvider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at GraphQL.AspNet.ApolloSubscriptionServerSchemaExtension`1.CreateSubscriptionServer(IServiceProvider sp)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)

         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)

```

Furthermore I will more than likely discuss flagged based enums as well... Because it does feed into this example...

Whether this helps or not... From my understanding (without looking throughout your code) KEY = uint/int/etc... VALUE=the label assigned? if this is correct then it should be supper to make the Value some list (assuming you are tracking it as a string) you could go through check on GraphQL object side if object attribute is list then the resulting C# Enum.HasFlag() and its value results to `X` ( | or all the keys in the map) if not then the input GraphQl data coming in would result to the Key in the map to which the Value contains the string.

Just a suggestion.. and maybe inaccurate/incomplete.

This is amazing!!! cheers.

**Comment by kevin-carroll** [comment] 2021-01-29 01:50
Great catch, this is indeed a bug!  The schema manager is correctly rejecting the graph type because it sees two enum options with the same key value of `First`, which from the graphQL specification is invalid.   

The problem is much earlier (and much deeper) in the schema setup process during templating when the enum itself is parsed. For some reason it currently sees the value `First` as 287 then when it sees 287 a second time it assigns the second value `First` as well instead of `NvUndefinedSpaceSpecial`.   Will need to investigate further and determine a fix.

Thanks for the assist!

**Comment by kevin-carroll** [comment] 2021-01-29 22:03
Unfortunately it looks like the fix will be to deny the enumeration from being used (i.e. fail the schema creation) if it contains duplicate values.  The underlying implementation (what is actually stored in memory) of any enum is its numerical root data type (int, uint etc.) and as such when consuming an enum value by either returning it from a controller method or assigning to a property of an object, at runtime, a application is in fact working with the numeric quantity. In the case of the example, the raw value `287` not the expected or supplied enum label of `First` or `NvUndefinedSpaceSpecial`. 

As a result, when the library goes to serialize data it knows which enum type its working with and it knows the value is 287 but it doesn't have enough context to determine "Is this 287 'First' or 'NvUndefined'?"  .NET simple does not make a distinction "at runtime".  The best it can do is ask the enum type "What name can you give to 287?".  Microsoft indicates that the enum will always respond with a name, but not guarantee which name (if duplicate values exist).  See the remarks section of [this page](https://docs.microsoft.com/en-us/dotnet/api/system.enum.getname?redirectedfrom=MSDN&view=net-5.0#System_Enum_GetName_System_Type_System_Object_).  

This can be illustrated by this code sample:
```
    class Program
    {
        public enum TestEnum
        {
            Value1 = 1,
            Value2 = 1,
            Value3 = 3,
        }

        static void Main(string[] args)
        {
            string value1Name = Enum.GetName(typeof(TestEnum), TestEnum.Value1);
            string value2Name = Enum.GetName(typeof(TestEnum), TestEnum.Value2);

            // true
            Console.WriteLine(value2Name == value1Name);
        }
    }
```

Since .NET does not make a runtime delineation between `Value1` and `Value2` (in the above example), but the graphql specification does, the expected behavior is to conform to the graphql specification and guarantee unique values server side when using an enum to match the expected unique values of the enum graph type in the specification.

**Fix to be implemented:**
A new validation check will be added at startup to ensure unique enum values for any used enumerations and throw a `GraphTypeDeclarationException`  (to replace the nebulous ArgumentException currently thrown)  with a detailed message indication which enum and what values failed.

**Comment by jasonkolodziej** [comment] 2021-01-29 23:30
Seems like its in `EnumGraphType.cs` and `GraphEnumOption.cs` however not sure about the specification that graphql writes.

**Comment by jasonkolodziej** [comment] 2021-01-29 23:30
> Seems like its in `EnumGraphType.cs` and `GraphEnumOption.cs` however not sure about the specification that graphql writes.

Which you might have already known that lol.

**Comment by kevin-carroll** [comment] 2021-01-29 23:57
:)  Right, those two objects deal with creating the introspection data for the schema and is part of the original problem you experienced.  But, the bigger concern is what having two enum values with the same root value causes downstream. 

Take for instance this controller:

```csharp
 public enum TestEnum
  {
      Value1 = 1,
      Value2 = 1,
      Value3 = 3,
  }

public class MyController : GraphController
{
   [QueryRoot]
   public IEnumerable<TestEnum> GetEnumValues()
  {
      var list = new List<TestEnum>();
      list.Add(TestEnum.Value1);
      list.Add(TestEnum.Value2);
      return list;
  }
}
```

and this query:
```graphql

-----------
query {
   getEnumValues
}
```

You would expect a data response of:
```json
{
  "data" :  {
     "getEnumValues" : [ "Value1", "Value2" ]
   }
}
```


But, your controller method returns what is essentially a list with 2 integers under the covers. In fact you could rewrite your controller as this and it would compile perfectly fine:
```csharp
public class MyController : GraphController
{
   [QueryRoot]
   public IEnumerable<TestEnum> GetEnumValues()
  {
      var list = new List<TestEnum>();
      list.Add((TestEnum)1);   // list.Add(TestEnum.Value1);
      list.Add((TestEnum)1);   // list.Add(TestEnum.Value2);
      return list;
  }
}
```

In this example there is no way to differentiate the two values, they are both the integer value `1`.  Since .NET doesn't support that use case and can't guarantee a correct labeling against the enumeration declaration we have to deny the potential obscurity in order to conform with the graphql specification.

A work around in your scenario may be to create some sort of mapping from your internal `Cc` enumeration and a different external enumeration that has unique values and is used in graph queries.

**Comment by kevin-carroll** [comment] 2021-02-06 16:48
fixed with release: https://github.com/graphql-aspnet/graphql-aspnet/releases/tag/v0.5.2-beta

**Closed by kevin-carroll** 2021-02-06 16:48 UTC
Labels: bug
