### ISSUE TITLE
Failed to pass nested object in Mutation Input Parameter

### ISSUE THREAD

**Issue by Pramod-Singh-30057234** [graphql-aspnet/graphql-aspnet#31] opened 2021-09-24 12:14 UTC
Dear Team,
I am creating a demo project in .Net Core 5 using this library. Failed in mutation when I passed nested object in parameter as inline. However it is working fine when I passed parameter by defining variable. Below are my code snippet 

[SourceCode.docx](https://github.com/graphql-aspnet/graphql-aspnet/files/7225524/SourceCode.docx)
[GraphAPI.zip](https://github.com/graphql-aspnet/graphql-aspnet/files/7225525/GraphAPI.zip)

**Comment by kevin-carroll** [comment] 2021-09-24 23:59
Hi @Pramod-Singh-30057234 ,

Thank you for supplying the write up and for including your graph query. In a quick test I was able to successfully reproduce the issue.  

This appears to be a bug in rule validator `5.6.4`.  It is wrongly assuming that each input type in the document must have at least one required field. Your `Address` object currently has 0 required fields which is perfectly fine but its causing the rule to fail.    

The reason you are able to pass it as a variable is because the variable values are not directly part of the query document and are evaluated/deserialized separately. This rule is targeted at the document text itself.

We'll get it fixed as soon as we can.

Cheers,
Kevin

**Comment by kevin-carroll** [comment] 2021-09-26 18:18
Bug fixed with release [v0.6.4-beta](https://github.com/graphql-aspnet/graphql-aspnet/releases/tag/v0.6.4-beta)

**Closed by kevin-carroll** 2021-09-26 18:18 UTC
Labels: bug

**Comment by Pramod-Singh-30057234** [comment] 2021-09-27 05:21
Thanks Kevin for quick fix. Now it is working fine.
